module.exports = {
 'identifier': ['(','+','-','*','/','=','[','=>','<','>','==','===','<=','>=','!=','!==',',','.','%','>>>=','>>=','<<=','>>>','>>','<<','^=','/=','*=','-=','+=','%=','|','||','|=','&','&&','&=','^','?',':',';','++','--'], 
 'await' : true,
 'boolean' : true,
 'break' : true,
 'byte' : true,
 'case' : true,	
 'catch' : true,
 'char' : true,	
 'class' : true,
 'const' : ['identifier'],
 'continue' : true,
 'debugger' : true,	
 'default' : true,	
 'delete' : true,	
 'do' : ['{'],
 'double' : true,
 'else' : ['{'],	
 'enum' : true,	
 'eval' : true,
 'export' : true,
 'extends' : true,	
 'false' : true,	
 'final' : true,
 'finally' : ['{'],	
 'float' : true,	
 'for' : '(',	
 'function' : ['identifier', '('],
 'goto' : true,	
 'if' : ['('],	
 'implements' : true,	
 'import' : true,
 'in' : true,	
 'instanceof' : true,	
 'int' : true,	
 'interface' : true,
 'let' : ['identifier'],
 'long' : true,	
 'native' : true,	
 'new' : true,
 'null' : true,
 'package' : true,	
 'private' : true,	
 'protected' : true,
 'public' : true,	
 'return' : true,	
 'short' : true,
 'static' : true,
 'super' : true,	
 'switch': true,	
 'synchronized': true,	
 'this': ['.'],
 'throw': true,
 'throws': true,
 'transient': true,
 'true': true,
 'try': ['{'],
 'typeof': ['identifier', '('],
 'var': ['identifier'],
 'void': true,
 'volatile': true,	
 'while': ['('],
 'with': true,
 'yield': true, 
 '=>': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal', 'key-word', '{'], //and a few key words
 '=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '<': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '>': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '==': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '<=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '>=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '===': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 '!': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '!=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 '!==': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '+': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '-': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '*': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '/': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 ',': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '.': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '%': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '~': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '?': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 ':': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 ';': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '&': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '&&': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 '|': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 	
 '||': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 '++': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 '--': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 '^': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 '&=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '|=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '%=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '+=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '-=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '*=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '/=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 '^=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '<<': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '>>': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '>>>': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], 
 '<<=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 '>>=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 '>>>=': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 '(': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'], //and a few key words
 ')': [],
 '[': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 ']': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 '{': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 '}': ['identifier','numeric-literal', 'string-literal', '(', 'template-literal'],
 'numeric-literal': ['+','-','*','/','=','=>','<','>','==','===','<=','>=','!=','!==',',','.','%','>>>=','>>=','<<=','>>>','>>','<<','^=','/=','*=','-=','+=','%=','|','||','|=','&','&&','&=','^','?',';','++','--'],
 'string-literal': ['+','-','*','/','=','=>','<','>','==','===','<=','>=','!=','!==',',','.','%','>>>=','>>=','<<=','>>>','>>','<<','^=','/=','*=','-=','+=','%=','|','||','|=','&','&&','&=','^','?',';','++','--'], 
 'template-literal': ['+','<','>','==','===','<=','>=','!=','!==',',','>>>=','>>=','<<=','>>>','>>','<<','+=','|','||','|=','&','&&','&=','?',';', ']']
}

let wow = cool;